### ISSUE TITLE
Vertaisarviointi #2

### ISSUE THREAD

**Issue by Saukka** [maariaw/character-chatter#2]
Sovelluksen idea on kiva ja kaikki sanotut valmiit ominaisuudet toimivat. Python koodi on jaettu eri tiedostoihin sopivasti. Suosittelen lisäämään lähetetyille viesteille myös tarkemman ajan päivän lisäksi. Toisena ehdotuksena, antaisin GM:lle vaihtoehdon valita näkeekö kaikki campaignissa olevat käyttäjät uuden chatin, vai vaan chatin osallistujat.

**Comment by maariaw** [comment]
Kiitos palautteesta! Toteutin ehdotetut ominaisuudet.
